In [14]:
import pandas as pd

# CSV 파일 불러오기
df1 = pd.read_csv('user_list_tv1.csv', encoding='utf-8-sig')
df2 = pd.read_csv('review_list_tv1.csv', encoding='utf-8-sig')

In [9]:
len(df1)

35

In [15]:
df2

                                                 User
0                gags\nIndia\nGenderMale\nAge25 to 34
1              Sushil\nDelhi\nGenderMale\nAge35 to 44
2             DSC\nHyderabad\nGenderMale\nAge35 to 44
3                                           Nikhilesh
4          Abhimanyu\nKanpur\nGenderMale\nAge25 to 34
5                   Prasanth\nGenderMale\nAge45 to 54
6           Satish\nkolhapur\nGenderMale\nAge45 to 54
7                        Gee\nGenderMale\nAge35 to 44
8                                           Madhu0117
9                  Anonymous\nGenderMale\nAge35 to 44
10                                             Manish
11          G max\nMangalore\nGenderMale\nAge35 to 44
12       Jay\nPandharapur MH\nGenderMale\nAge35 to 44
13     EmeraldWall\nHaldwani\nGenderMale\nAge25 to 34
14         Surag\nTrivandrum\nGenderMale\nAge45 to 54
15             Mitesh\nSurat\nGenderMale\nAge18 to 24
16           Saurabh\nJaipur\nGenderMale\nAge25 to 34
17                    Sravan\nGenderMale\nAge25 to 34
18                                      Tomm Dinakara
19                                               janu
20                  Ramesh T\nGenderMale\nAge35 to 44
21  Thiru123\nIndia hyderabad\nGenderMale\nAge25 t...
22           Japras\nJakarta\nGenderMale\nAge25 to 34
23  Anonymous\nHapur, U.P. India 245101\nGenderMal...
24            Mohan\nVellore\nGenderMale\nAge25 to 34
25  Manish\nGodda, jharkhand\nGenderMale\nAge25 to 34
26           Balaji\nChennai\nGenderMale\nAge25 to 34
27        Roshan\nTamil Nadu\nGenderMale\nAge25 to 34
28            Swapnil lingayat\nRatnagiri\nGenderMale
29          Buddy\nFaridabad\nGenderMale\nAge45 to 54
30            ctn\nbangalore\nGenderMale\nAge35 to 44

In [16]:
df2

                                               Review
0   1 out of 5 stars.\nSTAY AWAY FROM THESE TVS\n2...
1   1 out of 5 stars.\nPROBLEM IN PANEL WITHIN A W...
2   3 out of 5 stars.\nGOOD PICTURE QUALITY\n10 MO...
3   4 out of 5 stars.\nGREAT FEATURES, GOOD PICTUR...
4   4 out of 5 stars.\nILKE THIS LG TV\n8 DAYS AGO...
5   4 out of 5 stars.\n18 DAYS AGO\nProduct good b...
6   4 out of 5 stars.\n3 MONTHS AGO\nThe LED TV is...
7   4 out of 5 stars.\nGREAT VIEWING EXPERIENCE\n9...
8   4 out of 5 stars.\nGREAT PRODUCT IN THIS PRICE...
9   4 out of 5 stars.\nITS A FUN TV.\nA YEAR AGO\n...
10  5 out of 5 stars.\nGOOD VALUE FOR MONEY\n9 DAY...
11  5 out of 5 stars.\nGREAT PICTURE QUALITY AND E...
12  5 out of 5 stars.\nGREAT PRICE\n16 DAYS AGO\nI...
13  5 out of 5 stars.\nGOOD FEATURES AT REASONABLE...
14  5 out of 5 stars.\n6 MONTHS AGO\nvery good pro...
15  5 out of 5 stars.\nBEST TV\n6 MONTHS AGO\nI bo...
16  5 out of 5 stars.\nSUPPER\n6 MONTHS AGO\nI tak...
17  5 out of 5 stars.\nHAPPY WITH THE PURCHASE\n6 ...
18  5 out of 5 stars.\nELECTRIFYING TO OUR FAMILY....
19  5 out of 5 stars.\nGOOD\n7 MONTHS AGO\nDecent ...
20  5 out of 5 stars.\nGREAT\n8 MONTHS AGO\nBest t...
21  5 out of 5 stars.\nGREAT 4K TV\n9 MONTHS AGO\n...
22  5 out of 5 stars.\nLG LED\n9 MONTHS AGO\nGood ...
23  5 out of 5 stars.\nNC FUTURE\n9 MONTHS AGO\nHD...
24  5 out of 5 stars.\nULTIMAT PRODUCT\n10 MONTHS ...
25  5 out of 5 stars.\nGOOD\n11 MONTHS AGO\ngood s...
26  4 out of 5 stars.\nITS A FUN TV.\nEmeraldWall\...
27  1 out of 5 stars.\nGOT THE VA PANEL INSTEAD OF...
28  1 out of 5 stars.\nGOT THE VA PANEL INSTEAD OF...
29  3 out of 5 stars.\n20 HOURS AGO\nGood product,...
30  4 out of 5 stars.\nITS A FUN TV.\nEmeraldWall\...
31  1 out of 5 stars.\nGOT THE VA PANEL INSTEAD OF...
32  4 out of 5 stars.\nGREAT FEATURS\n29 DAYS AGO\...
33  4 out of 5 stars.\nGREAT FEATURES\n4 MONTHS AG...
34  5 out of 5 stars.\nRELEASE OF BONDS WITH THE B...